(define (compute a n)
  (let ((start-time (current-time)))
  (do ((i 1 (+ i 1)))
      ((> i n) 
       (let* ((end-time (current-time))
              (duration (time-difference end-time start-time)))
         (display "Result: ")
         (display a)
         (newline)
         (display "Time elapsed: ")
         (display duration)
         (newline)
         a))
    (set! a (* a i))))
(compute 7 77)
